on: [push, pull_request, workflow_dispatch]

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Lint Rust implementation
        run: cargo clippy

      - name: Check Rust format
        run: cargo fmt --check

      - name: Test Rust implementation
        run: cargo test --all-features
